In [1]:
#groupby()메서드 사용 
from pandas import Series, DataFrame
import numpy as np 

df = DataFrame({'key1':['a','a','b','b','a'], 
                'key2':['one','two','one','two','one'], 
                'data1':np.random.randn(5), 
                'data2':np.random.randn(5)})
df

  key1 key2     data1     data2
0    a  one -0.675269  2.243036
1    a  two  2.312389  0.484668
2    b  one -0.816910  0.008176
3    b  two -1.016668  1.662111
4    a  one  2.215798  0.661964

In [2]:
grouped = df.groupby("key1")["data1"]
grouped

In [20]:
print( grouped.mean() )
print( grouped.sum() )
print( grouped.count() )

key1
a    0.500867
b   -0.061464
Name: data1, dtype: float64
key1
a    1.502602
b   -0.122927
Name: data1, dtype: float64
key1
a    3
b    2
Name: data1, dtype: int64

In [23]:
#메서드체인(함수체인)
means = df.groupby( ["key2","key1"] )["data1"].mean()
means

key2  key1
one   a       0.014125
      b       0.033487
two   a       0.592620
      b      -0.627343
Name: data1, dtype: float64

In [2]:
#학급 성적 
dfClass = DataFrame({"학급":[1,1,2,2,1], 
    "이름":["홍길동","전우치","이순신","박문수","김길동"],
    "국어":[100,90,95,100,80], 
    "영어":[80,90,95,92,89], 
    "수학":[90,80,92,100,80]
    })

dfClass

   학급   이름   국어  영어   수학
0   1  홍길동  100  80   90
1   1  전우치   90  90   80
2   2  이순신   95  95   92
3   2  박문수  100  92  100
4   1  김길동   80  89   80

In [6]:
#합계
sum(dfClass["국어"])

465

In [7]:
#평균
sum(dfClass["국어"])/5

93.0

In [4]:
#오름차순
dfClass.sort_values("국어")

   학급   이름   국어  영어   수학
4   1  김길동   80  89   80
1   1  전우치   90  90   80
2   2  이순신   95  95   92
0   1  홍길동  100  80   90
3   2  박문수  100  92  100

In [9]:
#내림차순
dfClass.sort_values("국어", ascending=False)

   학급   이름   국어  영어   수학
0   1  홍길동  100  80   90
3   2  박문수  100  92  100
2   2  이순신   95  95   92
1   1  전우치   90  90   80
4   1  김길동   80  89   80

In [5]:
#새로운 컬럼 추가하기
dfClass["전체"] = dfClass["국어"] + dfClass["수학"] + dfClass["영어"]

In [6]:
#평균을 추가하기 
dfClass["평균"] = (dfClass["국어"] + dfClass["수학"] + dfClass["영어"])/3

In [7]:
dfClass

   학급   이름   국어  영어   수학   전체         평균
0   1  홍길동  100  80   90  270  90.000000
1   1  전우치   90  90   80  260  86.666667
2   2  이순신   95  95   92  282  94.000000
3   2  박문수  100  92  100  292  97.333333
4   1  김길동   80  89   80  249  83.000000

In [13]:
#내림차순 정렬하기 
dfClass.sort_values("평균", ascending=False)

   학급   이름   국어  영어   수학   전체         평균
3   2  박문수  100  92  100  292  97.333333
2   2  이순신   95  95   92  282  94.000000
0   1  홍길동  100  80   90  270  90.000000
1   1  전우치   90  90   80  260  86.666667
4   1  김길동   80  89   80  249  83.000000

In [10]:
#학급별로 그룹핑하기 
dfClass.groupby("학급")["영어"].count()

학급
1    3
2    2
Name: 영어, dtype: int64

In [11]:
dfClass.agg(수학평균=("국어","mean"))

        국어
수학평균  93.0

In [12]:
dfClass.groupby("학급").agg(수학평균=("수학","mean"))

         수학평균
학급
1   83.333333
2   96.000000

In [17]:
dfClass.groupby("학급").agg(국어평균=("국어","mean"), 
            수학평균=("수학","mean"),
            영어평균=("영어","mean"), 
            갯수=("학급","count"))

    국어평균       수학평균       영어평균  갯수
학급
1   90.0  83.333333  86.333333   3
2   97.5  96.000000  93.500000   2